### ISSUE TITLE
Does this work with WebExtensions?

### ISSUE THREAD

**Issue by Tehhund** [palant/autoinstaller#10]
I have a [WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) that installs correctly when I go to about:debugging and load it manually. But when I try to install it with this extension the installation fails (error code - 3). Does this support WebExtensions? It would be a really convenient way to test extensions on my phone.

**Comment by palant** [comment]
Yes, this definitely works - a WebExtension XPI isn't treated any differently from a classic extension. However, if signing is required Auto Installer will prompt whether you want to install your unsigned build as a temporary add-on.

Note that this extension will no longer work as of Firefox 57 - only Web Extensions will be allowed then, and this functionality cannot be implemented as a Web Extension. However, the [web-ext tool](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Getting_started_with_web-ext) has comparable functionality.

**Comment by Tehhund** [comment]
Thank you for the info. Sadly [according to this](https://github.com/mozilla/web-ext/issues/737) web-ext doesn't support Firefox on Android yet, which is what I'm trying to use, but hopefully they'll add it soon.

**Comment by palant** [comment]
I see. I wonder whether this can be made working by using an external adb tool and forwarding the ports 6000 and 6080 from the device to the local machine.

Either way, Extension Auto-Installer should work but I cannot really test it right now.

**Comment by Tehhund** [comment]
I actually tried that - I installed the autoinstaller on my phone's Firefox and pushed the packaged WebExtension to autointaller's port (from the phone to the phone). It said the WebExtension was corrupted. I suspect it was user error but I gave up on it at that point. It's also possible that autoinstaller was confused because WebExtensions can be packaged as .zip instead of .xpi.

**Comment by palant** [comment]
zip and xpi are the same thing, except for the file name that isn't being transferred. But if Firefox says that the extension is corrupt, then maybe it indeed got messed up in the transfer. Which tool are you using to upload the file?
