### ISSUE TITLE
posting a file from node request module does not seem to work

### ISSUE THREAD

**Issue by erikvold** [palant/autoinstaller#3]
I would think that this nodeJS script, `fs.createReadStream("foo.xpi").pipe(require("request").post("http://localhost:8888"))` should work, but I'm getting this error:

addons.xpi	WARN	Download of install-shortener:36 failed: [Exception... "Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [nsIZipReader.open]"  nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: AI_loadManifest :: line 5267"  data: no] Stack trace: AI_loadManifest()@resource://gre/modules/addons/XPIProvider.jsm:5267 < AI_onStopRequest()@resource://gre/modules/addons/XPIProvider.jsm:5540 < <file:unknown>

wget with the same file does work.

**Comment by erikvold** [comment]
I've tried a few other ways from node and I seem to have the same issue all of the time.

**Comment by twolfson** [comment]
I am having the same issue. I tried to reduce the issue to being in `node` but it looks like `curl` has the same issue:

```bash
$ curl http://localhost:8888/ --data '@dist/firefox-pinboard.xpi' --verbose
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8888
> Accept: */*
> Content-Length: 71163
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 500 No Content
< Connection: close
< Content-Length: 0
< 
* Closing connection 0
```

I think the issue is that `wget` pushes data no matter what whereas `request`/`curl` respect the 500 error.

Can we make it so the response header is sent after data is inbound? Or maybe add a configuration to set the response header to 204 (success, no content)?

**Comment by erikvold** [comment]
Hmm I don't think the issue is that the data is not sent, I logged the data retrieved by the autoinstaller add-on, and it appears to retrieve enough data, it seems that the data is different when using wget vs different node approaches that I've tried, so perhaps there is a way to get node to work without modifications to this repo?

**Comment by palant** [comment]
Yes, I see `NS_ERROR_FILE_CORRUPTED` on the console with curl - it's being received but something is wrong with it.

**Comment by palant** [comment]
Actually, curl doesn't actually send the data with the request - instead it adds an `Expect: 100-continue` header and expects the server to confirm the request (which it never does). The following command line works:

    curl http://localhost:8888/ --data-binary '@dist/firefox-pinboard.xpi' -H 'Expect:'

Note that I used the `--data-binary` flag - not sure what encoding it uses by default but that should be safe.

I'll add the notes on using curl to extension description.

**Comment by palant** [comment]
As to the `request` module, the problem there is a different one. If you pipe content into the request then the transfer encoding will be chunked. Processing chunks isn't something that Extension AutoInstaller currently supports and frankly - I don't think that this complexity is justified. You can easily work around this problem by reading the whole file into memory:

    require("request").post({url: "http://localhost:8888", body: fs.readFileSync("foo.xpi")});

**Comment by twolfson** [comment]
Wow, thanks for the detailed information and their solutions =)
