### ISSUE TITLE
My Addon isn't installed in Firefox

### ISSUE THREAD

**Issue by Tagaro** [palant/autoinstaller#4]
After runing this at the command line:
wget --post-file=RE.xpi http://localhost:8888/

I got the following:
alhost:8888/
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2015-01-25 00:31:35--  http://localhost:8888/
Resolving localhost... 127.0.0.1, ::1
Connecting to localhost|127.0.0.1|:8888... connected.
HTTP request sent, awaiting response... 500 No Content
2015-01-25 00:31:35 ERROR 500: No Content.

As I understand the '500 No Content' message is normal but my addon isn't installed in Firefox
I can install the xpi in Firefox fine and it shows up.

Can anyone help?

Update: I've downloaded the Ninja2 module that I didn't have before. I then went to download easy_install or setuptools but the instructions for dowloading / installing them redirects to each other. extremely comfusing and frustrating. I finally just uninstalled extension-auto installer being fedup and no help on this here.

**Comment by palant** [comment]
Jinja2 is only required to build Extension AutoInstaller yourself, it isn't necessary to use it.

Extension AutoInstaller will write messages to the Browser Console if something goes wrong - you can use Ctrl+Shift+J to open it. Not much I can do without seeing these messages but feel free to reopen if you have them.

Sorry but I cannot provide real support for Extension AutoInstaller - I'm doing this in my spare time.
