### ISSUE TITLE
Getting error after posting addon that I don't get on start.

### ISSUE THREAD

**Issue by e-motiv** [palant/autoinstaller#5]
jpm post together with autoinstaller worked fine before, but now I'm getting a weird error, supposed to be from my addon, but only after posting, not after restarting.  I'm trying to figure out why this error pops up after post and not otherwise.  Is it autoinstaller related or .. ?

Error:
```
aId is undefined

resource:///modules/CustomizableUI.jsm

"CustomizableUIInternal.isSpecialWidget
resource:///modules/CustomizableUI.jsm:1199:5CustomizableUIInternal.getWidgetProvider
resource:///modules/CustomizableUI.jsm:820:9CustomizableUIInternal.wrapWidget
resource:///modules/CustomizableUI.jsm:433:20this.CustomizableUI.createWidget
resource:///modules/CustomizableUI.jsm:3180:1create
resource://gre/modules/commonjs/sdk/ui/button/view.js:122:1BxTagButton<.initialize
resource://bookmarkstagsmix-at-e-motiv-dot-net/lib/BxTagButton.js:133:6constructor
resource://gre/modules/commonjs/sdk/core/heritage.js:146:23destroyAndRebuildTags/<
resource://bookmarkstagsmix-at-e-motiv-dot-net/index.js:34:15destroyAndRebuildTags
resource://bookmarkstagsmix-at-e-motiv-dot-net/index.js:32:2
resource://bookmarkstagsmix-at-e-motiv-dot-net/index.js:85:1run
resource://gre/modules/commonjs/sdk/addon/runner.js:145:19startup/</<
resource://gre/modules/commonjs/sdk/addon/runner.js:86:7Handler.prototype.process
resource://gre/modules/Promise-backend.js:867:23this.PromiseWalker.walkerLoop
resource://gre/modules/Promise-backend.js:746:7this.PromiseWalker.scheduleWalkerLoop/<
resource://gre/modules/Promise-backend.js:688:37Promise*this.PromiseWalker.scheduleWalkerLoop
resource://gre/modules/Promise-backend.js:688:5this.PromiseWalker.schedulePromise
resource://gre/modules/Promise-backend.js:709:7this.PromiseWalker.completePromise
resource://gre/modules/Promise-backend.js:671:7handler
resource://gre/modules/commonjs/sdk/addon/window.js:56:3"
```

**Comment by e-motiv** [comment]
After debugging somewhat, it seems that some special buttons that I create are still there when relaunching the xpi/addon update.  Should I solve this by implementing a "dispose" or something?  What does autoinstaller do before relaunching the update that covers this?

**Comment by e-motiv** [comment]
OK. I found it.
You have to dispose any view you create. For example via implementing "Disposable" interface and defining the "dispose" method in any view you create.
I hope this helps other people.
```
const { Disposable } = require('sdk/core/disposable');
const myView = Class({
	 implements: [
	              Disposable
	            ],
...
,
	  dispose: function dispose() {
	    view.dispose(this.id);
	  }
```

**Comment by palant** [comment]
This seems unrelated to autoinstaller - the add-on is simply producing an error when being updated in a live browser, because the "old" instance doesn't clean up after itself correctly.

**Comment by e-motiv** [comment]
Yeah, it's not a bug of autoinstaller, but it's related to how autoinstaller & firefox work together. 
Just saying so you can leave it here (or elsewhere) for other people to find the solution I found.

**Comment by palant** [comment]
No, it's merely related to updating restartless extensions - with autoinstaller or without it.

**Comment by e-motiv** [comment]
...on which autoinstaller relies.  Or...where autoinstaller relies on.
I mean, who knows what feature from firefox autoinstaller uses to do what
it does. You, obviously,but not everyone.
In still other words: maybe it's better to post this on a restartless
development forum, but I can guess that developers who use autoinstaller
may also look for the solution at autoinstaller support site, even if it's
not "merely" autoinstaller related.  (Also notice that on updating that
people willl experience the problem, and mostly other people, not the
developer himself, since he develops it and will probably not experience
his own bugs, because he doesn't do the firefox update from his own addon.)

So, what are you argumenting? That this "knowledge" can not be left here on
this issue thread?

Mvg,
   [image: Ruby Contact Card]
<http://www.e-motiv.net/Ruben%20Goethals%20-%20e-motiv.vcf>Ruben
<Ruben@e-motiv.net>    @   e-motiv <http://www.e-motiv.net>
 [image: Ruby] <http://www.e-motiv.net> +32  (0) 484  /  23 78 78
