### ISSUE TITLE
Very slow in Firefox nightly build

### ISSUE THREAD

**Issue by denizdogan** [palant/autoinstaller#6]
I'm using Firefox Nightly 44.0a1 (2015-10-14) because I am trying out the new ECMAScript class support. It's working fine, but Extension Auto-Installer is running very slowly, pretty much making Firefox stall completely for 10 seconds, every time I save a watched file. After this happens a few times, the browser even says that Extension Auto-Installer is making Firefox run slowly and suggests disabling it.

Is this a known issue and if so, what can I do about it?

**Comment by denizdogan** [comment]
I just found this blog post which is probably relevant in one way or another: https://blog.mozilla.org/addons/2015/10/14/breaking-changes-let-const-firefox-nightly-44/

I'll just wait with using Firefox 44 until some later time.

**Comment by palant** [comment]
No, Extension Auto-Installer isn't affected by this issue. And, no - I didn't notice such an extreme slowdown.

I assume that you are using JPM. When I install a fairly simple Add-on SDK extension the profiler shows that it keeps Firefox busy for 3 seconds. Almost 40% of the time is being spent in the SDK loader, reading in modules, plus 4% executing them. Another 20% are spent in the SDK unloader, cleaning up after the previous instance of that extension. Panel initialization code takes up 3.5%. And so on, none of the top CPU time consumers seem to be related to Extension Auto-Installer. Even XPIProvider.jsm and AddonManager.jsm are far down in the list, it's pretty much Add-on SDK everywhere.

Maybe you could create a profile of your own. You can open the [Browser Toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox), switch to the "Performance" tab and start recording. Then you update your extension and stop the recording once Firefox is responsive again. You don't need to interpret the data yourself - the profile can be saved to a file and I can take a look.

**Comment by denizdogan** [comment]
The profile data is almost 2 MB so I uploaded it to my Dropbox account: https://www.dropbox.com/s/enpujmowfi5t3io/profile.json?dl=0

This was with Firefox 44.0a1, and similar (if not the same) behavior can be seen in Firefox 42.0b6. It should probably be noted that I'm using the new class features from ECMAScript 6. I'm also on Windows 7 64-bit.

**Comment by palant** [comment]
Your profile shows almost 10 seconds being spent in the [AI_openChannel() function](http://hg.mozilla.org/mozilla-central/file/833c3c37daa6/toolkit/mozapps/extensions/internal/XPIProvider.jsm#l5305) and more than 4 seconds in Extension Auto-Installer ([function handler.newChannel()](https://github.com/palant/autoinstaller/blob/1.2.2/lib/urlShortener.js#L55)). Could it be that your add-on is very large? What's the size of the XPI file?

**Comment by denizdogan** [comment]
Hm, yeah, it's ~54 MB apparently, which it definitely shouldn't be. I unzipped it and found that I had accidentally included the entire Firefox nightly build directory, which is conveniently located in the project root directory. Oops! Sorry for the noise and thanks for the help!
