### ISSUE TITLE
Installation silently fails for unsigned addons in Firefox >=43

### ISSUE THREAD

**Issue by fhd** [palant/autoinstaller#7]
When posting an unsigned XPI to Auto-Installer in Firefox 43 with `xpinstall.signatures.required` set to `true` (the default), I only get a `309: No Content` response (the same response I get when the installation succeeds), but the extension doesn't get installed. After setting `xpinstall.signatures.required` to `false`, it works as usual.

I'm not sure how Auto-Installer should deal with `xpinstall.signatures.required`, but I think it should deal with it somehow, if only by mentioning it in the README.

**Comment by fhd** [comment]
Just read that [this pref is going to be removed in Firefox 46](https://blog.mozilla.org/addons/2016/01/22/add-on-signing-update/), then it's not really worth bothering with it. I  guess it makes more sense to look into [`jpm sign`](https://blog.mozilla.org/addons/2015/12/18/signing-firefox-add-ons-with-jpm-sign/).

**Comment by palant** [comment]
It rather makes sense to install the extension via `AddonMaanger.installTemporaryAddon()` which has been added in Firefox 45. However, this action needs to be confirmed by the user (requirement by Mozilla). I didn't have time to implement this functionality yet.

**Comment by kzar** [comment]
FWIW I just hit this too and found it kind of confusing. Would have been nice to get an error message, took me a while to realise it was failing.

**Comment by fhd** [comment]
Oh, nice! I have just come to terms with using Developer Edition for extension development, where `xpinstall.signatures.required` still exists :smile:

**Comment by palant** [comment]
Well, installing as temporary add-on isn't going to be quite as convenient - there has to be a prompt, silent installation isn't allowed for security reasons.
