### ISSUE TITLE
Fennec 53+

### ISSUE THREAD

**Issue by NiklasGollenstede** [palant/autoinstaller#9]
The compatibility of this very useful add-on is locked at version 52 for Firefox for Android, while all other platforms are not.
Is there a reason for that, or can you just update that number?

**Comment by palant** [comment]
I simply didn't get a chance to update compatibility info on AMO lately. This is the same for all platforms however, and that compatibility info normally shouldn't matter - the default policy is "compatible by default." Could it be that you enabled strict compatibility checking on Android somehow?

Either way, I've updated compatibility info now - all up to Firefox 54.

**Comment by NiklasGollenstede** [comment]
Thanks for the update!

> This is the same for all platforms however

It at least doesn't look that way on the screenshot below.

> and that compatibility info normally shouldn't matter

AMO didn't let me download the add-on in Fennec 53, at least not directly. The link was disabled.

![screenshot - feb 5 2017 11 26 pm](https://cloud.githubusercontent.com/assets/10552031/22630460/bccfbff8-ebfa-11e6-84c9-fdef92388627.png)

**Comment by palant** [comment]
Interesting. Yes, it seems that AMO still enforces strict compatibility for Android, good to know.
